const CONSTANTS = {
  SOCKET_SERVER_EVENTS: {
    NEW_MESSAGE: "NEW_MESSAGE",
    NEW_MESSAGE_SUCCESS: "NEW_MESSAGE_SUCCESS",
    NEW_MESSAGE_ERROR: "NEW_MESSAGE_ERROR",
    DELETE_MESSAGE: "DELETE_MESSAGE",
    DELETE_MESSAGE_SUCCESS: "DELETE_MESSAGE_SUCCESS",
    DELETE_MESSAGE_ERROR: "DELETE_MESSAGE_ERROR",
  },
};
module.exports = CONSTANTS;
